// <auto-generated />
using System;
using System.Collections.Generic;
using MRV.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MRV.Infrastructure.Migrations
{
    [DbContext(typeof(MRVDbContext))]
    [Migration("20260409100708_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MRV.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("SubmissionId")
                        .HasColumnType("text")
                        .HasColumnName("submission_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("HierarchyRank")
                        .HasColumnType("integer")
                        .HasColumnName("hierarchy_rank");

                    b.PrimitiveCollection<List<string>>("Permissions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("permissions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.SolarEnergyLoggingMonthly", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ElectricityBillImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("electricity_bill_image_url");

                    b.Property<double?>("EnergyConsumedFromGrid")
                        .HasColumnType("double precision")
                        .HasColumnName("energy_consumed_from_grid");

                    b.Property<double?>("EnergyExportedToGrid")
                        .HasColumnType("double precision")
                        .HasColumnName("energy_exported_to_grid");

                    b.Property<int>("Month")
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("SolarSystemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("solar_system_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.ToTable("solar_energy_logging_monthly", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.SolarSystem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly?>("GreenMeterConnectionDate")
                        .HasColumnType("date")
                        .HasColumnName("green_meter_connection_date");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date")
                        .HasColumnName("installation_date");

                    b.Property<string>("InstallationLocation")
                        .HasColumnType("text")
                        .HasColumnName("installation_location");

                    b.Property<double?>("InverterCapacity")
                        .HasColumnType("double precision")
                        .HasColumnName("inverter_capacity");

                    b.Property<string>("InverterSerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("inverter_serial_number");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MeterModel")
                        .HasColumnType("text")
                        .HasColumnName("meter_model");

                    b.Property<string>("MeterSerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("meter_serial_number");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Settlement")
                        .HasColumnType("text")
                        .HasColumnName("settlement");

                    b.Property<double?>("SolarPanelCapacity")
                        .HasColumnType("double precision")
                        .HasColumnName("solar_panel_capacity");

                    b.Property<string>("Tehsil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tehsil");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unique_identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("village");

                    b.HasKey("Id");

                    b.ToTable("solar_systems", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.Submission", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("text")
                        .HasColumnName("approved_by");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("OperatorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operator_id");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("record_id");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submission_type");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.UserTehsil", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("Tehsil")
                        .HasColumnType("text")
                        .HasColumnName("tehsil");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "Tehsil");

                    b.ToTable("user_tehsils", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.UserWaterSystem", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("WaterSystemId")
                        .HasColumnType("text")
                        .HasColumnName("water_system_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId", "WaterSystemId");

                    b.ToTable("user_water_systems", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.VerificationLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action_type");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("performed_by");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("SubmissionId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("verification_logs", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.WaterEnergyLoggingDaily", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("BulkMeterImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("bulk_meter_image_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<TimeOnly?>("PumpEndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("pump_end_time");

                    b.Property<double?>("PumpOperatingHours")
                        .HasColumnType("double precision")
                        .HasColumnName("pump_operating_hours");

                    b.Property<TimeOnly?>("PumpStartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("pump_start_time");

                    b.Property<string>("Remarks")
                        .HasColumnType("text")
                        .HasColumnName("remarks");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<double?>("TotalWaterPumped")
                        .HasColumnType("double precision")
                        .HasColumnName("total_water_pumped");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WaterSystemId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("water_system_id");

                    b.HasKey("Id");

                    b.HasIndex("WaterSystemId", "LogDate")
                        .IsUnique()
                        .HasDatabaseName("uq_water_energy_logging_daily_sid_date");

                    b.ToTable("water_energy_logging_daily", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.WaterSystem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CalibrationRequirement")
                        .HasColumnType("text")
                        .HasColumnName("calibration_requirement");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<double?>("DepthOfWaterIntake")
                        .HasColumnType("double precision")
                        .HasColumnName("depth_of_water_intake");

                    b.Property<double?>("HeightToOhr")
                        .HasColumnType("double precision")
                        .HasColumnName("height_to_ohr");

                    b.Property<DateOnly?>("InstallationDate")
                        .HasColumnType("date")
                        .HasColumnName("installation_date");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("MeterAccuracyClass")
                        .HasColumnType("text")
                        .HasColumnName("meter_accuracy_class");

                    b.Property<string>("MeterModel")
                        .HasColumnType("text")
                        .HasColumnName("meter_model");

                    b.Property<string>("MeterSerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("meter_serial_number");

                    b.Property<double?>("PumpFlowRate")
                        .HasColumnType("double precision")
                        .HasColumnName("pump_flow_rate");

                    b.Property<string>("PumpModel")
                        .HasColumnType("text")
                        .HasColumnName("pump_model");

                    b.Property<string>("PumpSerialNumber")
                        .HasColumnType("text")
                        .HasColumnName("pump_serial_number");

                    b.Property<string>("Settlement")
                        .HasColumnType("text")
                        .HasColumnName("settlement");

                    b.Property<DateOnly?>("StartOfOperation")
                        .HasColumnType("date")
                        .HasColumnName("start_of_operation");

                    b.Property<string>("Tehsil")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tehsil");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("unique_identifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("village");

                    b.HasKey("Id");

                    b.ToTable("water_systems", (string)null);
                });

            modelBuilder.Entity("MRV.Domain.Entities.User", b =>
                {
                    b.HasOne("MRV.Domain.Entities.Role", "AssignedRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedRole");
                });

            modelBuilder.Entity("MRV.Domain.Entities.UserTehsil", b =>
                {
                    b.HasOne("MRV.Domain.Entities.User", null)
                        .WithMany("TehsilLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MRV.Domain.Entities.UserWaterSystem", b =>
                {
                    b.HasOne("MRV.Domain.Entities.User", null)
                        .WithMany("WaterSystemLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MRV.Domain.Entities.User", b =>
                {
                    b.Navigation("TehsilLinks");

                    b.Navigation("WaterSystemLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
